@host = http://localhost:3000

GET {{host}}/api/author
###

GET {{host}}/api/author?limit=2

###

GET {{host}}/api/author?page=2&limit=3

###

POST {{host}}/api/author
Content-Type: application/json

{
    "name": "José García",
    "email": "jose__@example.com",
    "image": "jose.jpg"
}

###

GET {{host}}/api/post

###

GET {{host}}/api/post?groupedByAuthor=true

###

GET {{host}}/api/post?limit=3

###

GET {{host}}/api/post?page=2&limit=3
###

GET {{host}}/api/post?groupedByAuthor=true&page=2&limit=3

###

GET {{host}}/api/post/1

###

GET {{host}}/api/post/1?limit=2

###

GET {{host}}/api/post/1?page=2&limit=2

###

POST {{host}}/api/post
Content-Type: application/json

{
    "title": "_Aprendiendo Node.js con ejemplos",
    "description": "Este post explica cómo comenzar a usar Node.js con proyectos reales.",
    "category": "Desarrollo Web",
    "author_id": 1
}

###